Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# create tables
cur.execute("""
CREATE TABLE Location (
  ZipCode TEXT PRIMARY KEY,
  Country TEXT,
  State TEXT,
  City TEXT,
  Latitude REAL,
  Longitude REAL
);
""")

cur.execute("""
CREATE TABLE Customer (
    CustomerID TEXT PRIMARY KEY,
    Gender TEXT,
    SeniorCitizen TEXT,
    Partner TEXT,
    Dependents TEXT,
    Churn TEXT,
    ZipCode TEXT,
    ChurnLabel TEXT,
    ChurnValue INTEGER,
    ChurnScore INTEGER,
    CLTV INTEGER,
    ChurnReason TEXT,
    FOREIGN KEY (ZipCode) REFERENCES Location(ZipCode)
);
""")

cur.execute("""
CREATE TABLE Services (
  CustomerID TEXT PRIMARY KEY,
  TenureMonths INTEGER,
  PhoneService TEXT,
  MultipleLines TEXT,
  InternetService TEXT,
  OnlineSecurity TEXT,
  OnlineBackup TEXT,
  DeviceProtection TEXT,
  TechSupport TEXT,
  StreamingTV TEXT,
  StreamingMovies TEXT,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);
""")

cur.execute("""
CREATE TABLE Billing (
  CustomerID TEXT PRIMARY KEY,
  Contract TEXT,
  PaperlessBilling TEXT,
  PaymentMethod TEXT,
  MonthlyCharges REAL,
  TotalCharges REAL,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);
""")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOperationalError[0m                          Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m [38;5;66;03m# create tables[39;00m
[0;32m----> 2[0m [43mcur[49m[38;5;241;43m.[39;49m[43mexecute[49m[43m([49m[38;5;124;43m"""[39;49m
[1;32m      3[0m [38;5;124;43mCREATE TABLE Location ([39;49m
[1;32m      4[0m [38;5;124;43m  ZipCode TEXT PRIMARY KEY,[39;49m
[1;32m      5[0m [38;5;124;43m  Country TEXT,[39;49m
[1;32m      6[0m [38;5;124;43m  State TEXT,[39;49m
[1;32m      7[0m [38;5;124;43m  City TEXT,[39;49m
[1;32m      8[0m [38;5;124;43m  Latitude REAL,[39;49m
[1;32m      9[0m [38;5;124;43m  Longitude REAL[39;49m
[1;32m     10[0m [38;5;124;43m);[39;49m
[1;32m     11[0m [38;5;124;43m"""[39;49m[43m)[49m
[1;32m     13[0m cur[38;5;241m.[39mexecute([38;5;124m"""[39m
[1;32m     14[0m [38;5;124mCREATE TABLE Customer ([39m
[1;32m     15[0m [38;5;124m    CustomerID TEXT PRIMARY KEY,[39m
[0;32m   (...)[0m
[1;32m     28[0m [38;5;124m);[39m
[1;32m     29[0m [38;5;124m"""[39m)
[1;32m     31[0m cur[38;5;241m.[39mexecute([38;5;124m"""[39m
[1;32m     32[0m [38;5;124mCREATE TABLE Services ([39m
[1;32m     33[0m [38;5;124m  CustomerID TEXT PRIMARY KEY,[39m
[0;32m   (...)[0m
[1;32m     45[0m [38;5;124m);[39m
[1;32m     46[0m [38;5;124m"""[39m)

[0;31mOperationalError[0m: table Location already exists

